//TAB
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const SET_ACTIVE_TAB_MENU_PROFILE = "SET_ACTIVE_TAB_MENU_PROFILE";

//INFO DETAIL
export const SET_ACTIVE_INFO_DETAIL = "SET_ACTIVE_INFO_DETAIL";
export const SET_ACTIVE_INFO_ITEM = "SET_ACTIVE_INFO_ITEM";

//USER
export const GET_USER_ALL = "GET_USER_ALL";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "UPDATE_USER";
export const GET_USER_LOGIN_INFO = "GET_USER_LOGIN_INFO";
export const GET_USERS_J0IN_IN_PROJECT = "GET_USERS_J0IN_IN_PROJECT";

//STORE
export const GET_DETAIL_STORE = "GET_DETAIL_STORE";

// THEME
export const SET_THEME = "SET_THEME";
